//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.HotelServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HotelModel", Namespace="http://schemas.datacontract.org/2004/07/WcfHotelService")]
    [System.SerializableAttribute()]
    public partial class HotelModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HotelIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HotelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double HotelRatingField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelAddress {
            get {
                return this.HotelAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelAddressField, value) != true)) {
                    this.HotelAddressField = value;
                    this.RaisePropertyChanged("HotelAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HotelID {
            get {
                return this.HotelIDField;
            }
            set {
                if ((this.HotelIDField.Equals(value) != true)) {
                    this.HotelIDField = value;
                    this.RaisePropertyChanged("HotelID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HotelName {
            get {
                return this.HotelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HotelNameField, value) != true)) {
                    this.HotelNameField = value;
                    this.RaisePropertyChanged("HotelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double HotelRating {
            get {
                return this.HotelRatingField;
            }
            set {
                if ((this.HotelRatingField.Equals(value) != true)) {
                    this.HotelRatingField = value;
                    this.RaisePropertyChanged("HotelRating");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HotelServiceReference.IHotelOperations")]
    public interface IHotelOperations {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetHotelByID", ReplyAction="http://tempuri.org/IHotelOperations/GetHotelByIDResponse")]
        string GetHotelByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetHotelByID", ReplyAction="http://tempuri.org/IHotelOperations/GetHotelByIDResponse")]
        System.Threading.Tasks.Task<string> GetHotelByIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetAllHotel", ReplyAction="http://tempuri.org/IHotelOperations/GetAllHotelResponse")]
        Client.HotelServiceReference.HotelModel[] GetAllHotel();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHotelOperations/GetAllHotel", ReplyAction="http://tempuri.org/IHotelOperations/GetAllHotelResponse")]
        System.Threading.Tasks.Task<Client.HotelServiceReference.HotelModel[]> GetAllHotelAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHotelOperationsChannel : Client.HotelServiceReference.IHotelOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HotelOperationsClient : System.ServiceModel.ClientBase<Client.HotelServiceReference.IHotelOperations>, Client.HotelServiceReference.IHotelOperations {
        
        public HotelOperationsClient() {
        }
        
        public HotelOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HotelOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HotelOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetHotelByID(int id) {
            return base.Channel.GetHotelByID(id);
        }
        
        public System.Threading.Tasks.Task<string> GetHotelByIDAsync(int id) {
            return base.Channel.GetHotelByIDAsync(id);
        }
        
        public Client.HotelServiceReference.HotelModel[] GetAllHotel() {
            return base.Channel.GetAllHotel();
        }
        
        public System.Threading.Tasks.Task<Client.HotelServiceReference.HotelModel[]> GetAllHotelAsync() {
            return base.Channel.GetAllHotelAsync();
        }
    }
}
